#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use RodrigoPedra\RecordProcessor\Examples\ExamplesCommand;
use RodrigoPedra\RecordProcessor\Examples\DownloadCommand;

$application = new Application();

$application->add(new ExamplesCommand);
$application->add(new DownloadCommand);

$application->run();
